### ISSUE TITLE
Usage of deprecated securesystemslib exception

### ISSUE THREAD

**Issue by wickeat** [dennisvang/tufup#138]
**Describe the bug**
The current requirement on [securesystemslib](https://github.com/dennisvang/tufup/blob/4bb16ad228b4b6f39e42527cc4367e501d728142/pyproject.toml#L25) of >= 0.26.0 will automatically use the latest version of the package. In the latest 1.0.0 version, the CryptoError exception used [here in the code base](https://github.com/dennisvang/tufup/blob/4bb16ad228b4b6f39e42527cc4367e501d728142/src/tufup/repo/__init__.py#L17) has been removed from the securesystemslib’s latest [commit](https://github.com/secure-systems-lab/securesystemslib/commit/51bb41c1868b9425d18d9fe08489119f4b8c969d).

**To Reproduce**
1. Import tufup 
2. Observe the error on securesystemslib, eg. 
`from tufup.client import Client
b142df1c\Lib\site-packages\tufup\__init__.py:4: in <module>
    from tufup.repo import cli
b142df1c\Lib\site-packages\tufup\repo\__init__.py:17: in <module>
    from securesystemslib.exceptions import CryptoError
E   ImportError: cannot import name 'CryptoError' from 'securesystemslib.exceptions' `

**Expected behavior**
No error on import.

**Comment by dennisvang** [comment]
@wickeat I guess this is related to #133 and should be fixed with the latest version of tufup ([v0.8.0][1]).

Could you try that and let us know the result?

[1]: https://github.com/dennisvang/tufup/releases/tag/v0.8.0

**Comment by wickeat** [comment]
Yes, latest version of tufup ([v0.8.0](https://github.com/dennisvang/tufup/releases/tag/v0.8.0)) works. Thanks for the new info on tuf 5.0!

**Comment by dennisvang** [comment]
@wickeat Thanks for the feedback. :)
