### ISSUE TITLE
rename notsotuf

### ISSUE THREAD

**Issue by dennisvang** [dennisvang/tufup#23]
As mentioned in the README, *after* creating and publishing the initial version of `notsotuf`, I found out that there once existed another package called [Not-So-TUF][1]. Moreover it seems this was actually the [original name for PyUpdater][2].

Although this is a coincidence, and the not-so-tuf name seems to have been abandoned, it still doesn't feel right to continue using it.

Therefore I propose to rename the github repo and corresponding package from `notsotuf` to `tufup`. Short for TUF-updater, or tuffen-up or whatever you like. It is a bit shorter, which is convenient. 

I decided against `tuf-up` because I don't like hyphens in package names and want repository name and package name to match, to prevent ambiguity.

As there don't seem to be any users yet, now would be a good time to make this change.

@NicklasTegner  Sorry for the inconvenience.

[1]: https://pythonhosted.org/not-so-tuf/
[2]: https://github.com/Digital-Sapphire/PyUpdater/issues/87#issuecomment-361034435

**Comment by NicklasTegner** [comment]
A very late no problem here haha. Besides notsotuf is also kinda long to type in a terminal haha
