### ISSUE TITLE
Not Responding Progress Hook

### ISSUE THREAD

**Issue by abenzick** [dennisvang/tufup#34]
I'm using the progress hook to send updates to a GUI progress bar to provide feedback to users as the update is being downloaded. 

`client.download_and_apply_update(progress_hook=progress_hook)`

I then have the progress_hook for processing the data.

```
def progress_hook(bytes_downloaded, bytes_expected):
          progress_percent = bytes_downloaded / bytes_expected * 100
          self.onProgress(progress_percent)
          if progress_percent >= 100:
              print("Update has finished")
              self.thread_finished()  
              buttonUpdate = QMessageBox.information(self,'Update Success!', "AMP was updated successfully. Please start the app again.", QMessageBox.StandardButton.Ok, QMessageBox.StandardButton.Ok)
              if buttonUpdate == QMessageBox.StandardButton.Ok:
                  sys.exit()
```

Instead of being able to update, this function just locks up and never gets called and receives the hook data

![progress](https://user-images.githubusercontent.com/7201203/186981545-ea4f8e78-7238-43ce-bc6d-b90f9a8a960b.png)

Any thoughts? The update downloads fine. It just doesn't call the hook.

**Comment by dennisvang** [comment]
@abenzick It's a bit difficult to see what's going on without proper code formatting. Could you edit your post and put the code in a code block (i.e. enclosed in triple backticks: ```)?

**Comment by dennisvang** [comment]
@abenzick Could you also fix the indentation?

And your code raises some more questions:
- What is `self` in this context?
- What does `onProgress()` do?
- What does `thread_finished()` do?
- Why do you call `sys.exit()` in the progress hook?

Assuming you're using a `QProgressBar`, basically all the progress hook should do is update the current value using`QProgressBar.setValue()`.

See [Qt docs for QProgressBar][1]

[1]: https://doc-snapshots.qt.io/qt6-dev/qprogressbar.html#details

**Comment by dennisvang** [comment]
Keep in mind the hooks gets called after every downloaded chunk, so that's many times in a row.

Also, have a look at the [progress hook from tufup-example][1]: basically you should just replace the `print` calls by a call to your `QProgressBar`'s `setValue()`, using `progress_percent` as the value.

(assuming you've specified the progress bar's min and max values to be 0 and 100, respectively)

[1]: https://github.com/dennisvang/tufup-example/blob/ce49f3dee1daa86b19915c2b6d58620a1f199951/src/myapp/__init__.py#L14

**Comment by abenzick** [comment]
The other functions are from other parts of the app that are using the progress bar for other uses:

'''
def onProgress(self,i):
        # Worker thread has an update, increase the progress bar
        self.progress_bar.progressBar.setProperty("value", i)

    def thread_finished(self):
        # Worker thread is finished. Put any cleanup here
        print("Thread finished!")
        self.progress_bar.progressBar.setProperty("value", 0)
        self.progress_bar.close()
'''
I'm building a little test loop for the progress bar outside of client.download_and_apply_update

```
temp_counter = 0
                    while(temp_counter < 100):
                        progress_hook(temp_counter,100)
                        temp_counter+=1
                        time.sleep(0.5)  # quick and dirty: simulate slow or large download
```

**Comment by abenzick** [comment]
Well, my test loop for the progress bar didn't work so I clearly have a problem on my end outside of the tufup functions. I will grind it out and track it down :)

**Comment by abenzick** [comment]
Alright, my test loop problem was a PyQT problem.  It was fixed by adding the following to my loop:

`QApplication.processEvents() `

Now to see if the `client.download_and_apply_update` works and feeds the progress_hook

**Comment by abenzick** [comment]
All good, problem was entirely on my end. `QApplication.processEvents()` got my GUI where it needs to be and tufup feeding the progress_hook looks beautiful :)

**Comment by abenzick** [comment]
@dennisvang Check out what I've put together so far with the progress bar. I give a prompt when an update is detected, show the progress bar and then provide a confirmation that the update was downloaded successfully. It looks like a cmd prompt looking window comes up as the actual patch is being applied.

Do you have any tips or tricks to optimize this from a user perspective? I'm overall really happy about being able to integrate this functionality!

https://user-images.githubusercontent.com/7201203/187053035-a42ab98a-b78d-416d-ac0d-f6ff82c20656.mp4

**Comment by dennisvang** [comment]
@abenzick Good to hear you got it working. That progress bar looks very nice! :)

Tufup's default install script for windows opens a [new console][1] window and runs [robocopy][2] there ([docs][3]).

Although it is possible to hide the console by specifiying other `subprocess` [creationflags][4], the reason I used a visible console is to inform the user that the installation (i.e. copying of files) is still in progress.

[1]: https://github.com/dennisvang/tufup/blob/bb7b42004a6621a254aa5559a6019092839705db/src/tufup/utils/platform_specific.py#L124
[2]: https://github.com/dennisvang/tufup/blob/bb7b42004a6621a254aa5559a6019092839705db/src/tufup/utils/platform_specific.py#L52
[3]: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy
[4]: https://docs.python.org/3/library/subprocess.html#windows-constants

**Comment by abenzick** [comment]
That works just fine for me. I think it's reasonable!

**Comment by dennisvang** [comment]
Thanks. Closing this issue now.
