### ISSUE TITLE
timestamp.json is expired

### ISSUE THREAD

**Issue by abenzick** [dennisvang/tufup#36]
This is going to fall more into a procedural question than a problem with tufup, but I believe this could be helpful to others as well. I'm experiencing problems with my .exe failing with "timestamp.json is expired" when it begins a `.check_for_udpates()`. 

I've followed the feedback from [The Update Framework's Frequently Asked Questions](https://theupdateframework.io/faq/) where it recommends having timestamp.json expiring after a day.  

> The Timestamp and Snapshot metadata should normally have a short expiration (1 day), whereas the Root and Targets metadata should expire less often (1 year). A good rule of thumb is the more often the metadata changes, the sooner it should expire.

So, my timestamp is reporting it's expired as expected with it being set for a day. It's keeping my executable from now running. I am completely missing what is supposed to be resigning the timestamp.json after one day?

I have my metadata files hosted in an S3 bucket that the app is checking for updates. What is the process to keep the file signed and updated and the executable not failing?

**Comment by dennisvang** [comment]
> So, my timestamp is reporting it's expired as expected with it being set for a day. It's keeping my executable from now running. 

@abenzick Are you using `refresh_required=True`?

**Comment by abenzick** [comment]
@dennisvang No, I have it set to False. The error is getting caught on a try/except close.

My problem is why is the timestamp.json expired? Is it ok to ignore this? How will a new update every be triggered? Does it stay expired until a new update is put out and then it is caught?

**Comment by abenzick** [comment]
Thank you. I haven't seen any discussions on practical applications or procedures for how people manage the signing of the files. Having a cron job or similar functionality like that make sense.

**Comment by dennisvang** [comment]
@abenzick [PEP458][1] discusses the integration of TUF with PyPi (a public package repository). Although PyPi represents a *much more complex* use case than ours, the document does discuss the signing process, and I think it gives a good impression of some of the security trade offs.

[1]: https://peps.python.org/pep-0458/

**Comment by dennisvang** [comment]
Closing this for now. Feel free to re-open if you have any other questions.
