### ISSUE TITLE
Timeout variable for retrying patch when process still open

### ISSUE THREAD

**Issue by abenzick** [dennisvang/tufup#42]
Feature request:

One thing I've learned from the logging is why the update always takes 30 extra seconds. 

From the log file:

```
2022/09/22 20:11:20 ERROR 32 (0x00000020) Copying File C:\Users\aaronb\AppData\Local\Temp\tufup\AMP.exe
The process cannot access the file because it is being used by another process.

Waiting 30 seconds... Retrying...
	    Older     		  62.8 m	AMP.exe
  1.5%
  3.1%
  4.7%

```
It seems like every time it starts the patch process it detects the app is still running, waits 30 seconds and then is able to patch. 

Would it be possible to get a variable to set the timeout option so I can make it a little quicker than 30 seconds?

**Comment by dennisvang** [comment]
@abenzick Just released 0.4.2, which uses a 2 second retry-timeout for robocopy (instead of the default 30s).

In case someone wants to set a shorter/longer retry-timeout, the override [described above][1] can be used.

[1]: https://github.com/dennisvang/tufup/issues/42#issuecomment-1255905140
