### ISSUE TITLE
Can .zip be used?

### ISSUE THREAD

**Issue by its-monotype** [dennisvang/tufup#43]
On Windows we don't use tar.gz, usually .zip how can you use .zip for targets with your package?

**Comment by its-monotype** [comment]
I want to be able to send my users a zip archive containing the application's .exe file.

**Comment by dennisvang** [comment]
@its-monotype No, `zip` is not supported.

Windows powershell can extract `.tar.gz` files just as well, using the `tar -xf <file path>` command see e.g. [1]. You can call the `tar` command from inside you installer script, for example. (that's what we do)

If you really want to use `zip`, you could extract the `.tar.gz` from the targets folder yourself, and repack its contents as a `.zip` for distribution. This step is easy to automate as part of your build process.

Note that this is only relevant for *initial* distribution of your app. After initial distribution, the automated update process takes over, which always uses `.tar.gz` in the background.

[1]: https://ss64.com/nt/tar.html

**Comment by its-monotype** [comment]
@dennisvang Yes, I want to use .zip because for my users it's an extra step to unpack .tar.gz with cmd, and .zip can be easily decompressed through the Windows interface without using the command line. And you write that I can only make the initial archive in .zip. And if I can use .zip only for the initial version of the app, then it turns out that I won't be able to use your library. And how I can provide the very initial app version for download to users, because if I have a lot of new versions then they will wait until the last update is downloaded, it's also an extra step, or did I misunderstand smth?

**Comment by dennisvang** [comment]
> @dennisvang Yes, I want to use .zip because for my users it's an extra step to unpack .tar.gz with cmd, and .zip can be easily decompressed through the Windows interface without using the command line.

@its-monotype Yes, it is true that `zip` can be extracted more easily in Windows. If that is your preferred way of distributing your app, you can unpack the `.tar.gz` and repack as `.zip`, as described above. You can do this automatically, as part of your build process, so it should not take much effort.

Some alternative ways to hide the `.tar.gz` from the end-user would be:
- create a batch file that unpacks the `.tar.gz` (by calling the powershell tar command)
- create an installer, e.g. using [NSIS][1] or [Inno Setup][2]

> And you write that I can only make the initial archive in .zip. And if I can use .zip only for the initial version of the app, then it turns out that I won't be able to use your library. 

There seems to be a misunderstanding here: I wrote "Note that this is only relevant for initial distribution of your app."

By *"initial distribution"* I mean the very first time your user obtains  your app. So, maybe they downloaded it from your website, or they got it through some other channel. That is the only time they will need to do any manual unpacking/installation, so it is the only time they will actually see your `.zip` file.

Once your app is "installed" on the user's system, `tufup` will take care of updates, so your user will not need to worry about whether it's a `.zip` or `.tar.gz` archive. 

So, as long as you re-pack the `.tar.gz` to `.zip` for *every new release*, you should be able to use `tufup`.

> And how I can provide the very initial app version for download to users, because if I have a lot of new versions then they will wait until the last update is downloaded, it's also an extra step, or did I misunderstand smth?

The initial distribution of your app falls outside the scope of `tufup`. You could e.g. make the `.zip` files (for all your releases) available on your web site. Like this, for example: https://www.python.org/downloads/

[1]: https://nsis.sourceforge.io/Main_Page
[2]: https://jrsoftware.org/isinfo.php

**Comment by its-monotype** [comment]
Okay, I'll try, thank you so much for feedback
