### ISSUE TITLE
AttributeError: 'Root' object has no attribute 'revoke_key'. Did you mean: 'remove_key'?

### ISSUE THREAD

**Issue by its-monotype** [dennisvang/tufup#44]
"To get started, create a local example repository by running the
# repo_workflow_example.py script."
I run repo_workflow_example  and this error appeared
![image](https://user-images.githubusercontent.com/79363260/192118210-c45950c9-1b98-48ed-91fe-ea983fb87a17.png)

**Comment by dennisvang** [comment]
@its-monotype Looks like you're running an old version of `python-tuf`.

`remove_key` was renamed to `revoke_key` in [python-tuf 2.0.0][1]

[1]: https://github.com/theupdateframework/python-tuf/blob/v2.0.0/docs/CHANGELOG.md

**Comment by its-monotype** [comment]
@dennisvang 
![Screenshot 2022-09-26 120539](https://user-images.githubusercontent.com/79363260/192250069-20692129-5619-4f1e-81ea-5f9ff1e39be4.png)
I manually updated tuf but you have some kind of dependency problem...

**Comment by dennisvang** [comment]
@its-monotype Not sure where that comes from, but your error message says 
> tufup 0.4.2 requires tuf==1.1.* ...

However, clearly, that's not true:

https://github.com/dennisvang/tufup/blob/0cfa708334e7df6f122d60d67c819ad030bfdb91/requirements.txt#L8

I think the best approach is:
- make sure you have the latest version of the `tufup` source code
- create a new `venv` from scratch
- install dependencies from the latest `requirements.txt` and `requirements-dev.txt`

**Comment by dennisvang** [comment]
@its-monotype By the way, I see [your prompt][1] now says `tufup-example`. 

Is this a `tufup` issue or a `tufup-example` issue?

Are your running the right `venv`?

[1]: https://github.com/dennisvang/tufup/issues/44#issuecomment-1257799668

**Comment by its-monotype** [comment]
The same problem is there and there, when I install tufup, it installs tuf 1.x.x as a dependency and not the 2.x.x.

**Comment by its-monotype** [comment]
Yep, I understand, I want to say that I think it's tufup package related issue that when you do pip install tufup install as dependency tuf 1.x.x version and not the 2.x.x

**Comment by dennisvang** [comment]
The fact that `tufup` CI tests on Github all pass indicates that there is no dependency issue there.

I also verified `tufup-example` dependencies can be installed without issue in a fresh `venv`.

**Comment by its-monotype** [comment]
I mean if I just install tufup it installs as a dependency of tuf-1.1.0. I don't clone any repositories, I just write pip install tufup.

**Comment by dennisvang** [comment]
@its-monotype You're absolutely right.

This is quite embarassing: I forgot to update the `tuf` version in [setup.cfg][1].

This slipped through the cracks somehow...

Sorry for this. I'll fix it a.s.a.p.

[1]: https://github.com/dennisvang/tufup/blob/ba4ab2a3e2fb2a76ef534a77d726c7cb4b768cad/setup.cfg#L27

**Comment by dennisvang** [comment]
@its-monotype A new release is now available which should fix this issue: 0.4.3
