### ISSUE TITLE
Use relative paths in .tufup-repo-config

### ISSUE THREAD

**Issue by dennisvang** [dennisvang/tufup#50]
### Background
The `.tufup-repo-config` file, that is created when initializing a repository, includes absolute paths for the `keys_dir` and `repo_dir`.

Although these can easily be modified, when necessary, the file should be portable out-of-the-box.

### Proposal
It would be more convenient to use relative paths in the `.tufup-repo-config` file. That is, relative to the config file location.

**Comment by wickeat** [comment]
This enhancement would be great in making the implementation portable across different environments! Currently, I am manually editing the `keys_dir` and `repo_dir` of the `.tufup-repo-config` file.

**Comment by dennisvang** [comment]
@wickeat This was a bit tougher than expected. Perhaps you could have a look at #78 to see if the proposed solution would work for your case?
