### ISSUE TITLE
Update Version Summary?

### ISSUE THREAD

**Issue by abenzick** [dennisvang/tufup#51]
Hello, is there a way to see a summary of new things added in the updated versions? As I'm pretty new with this framework I'd like to be able to see a broad summary of the updates so I know about potential impacts to my workflow.

**Comment by dennisvang** [comment]
@abenzick Would the [releases page][1] help?

You can find more detail for individual releases by clicking on the corresponding "Full changelog" links.

[1]: https://github.com/dennisvang/tufup/releases

**Comment by abenzick** [comment]
Yes, that works just fine. I wasn't able to find it from the Github main pages. I'm not as well versed. Thank you!

**Comment by dennisvang** [comment]
@abenzick No problem. :-) I'll close the issue now.
