### ISSUE TITLE
Migrating from Pyupdater

### ISSUE THREAD

**Issue by KelvinSan** [dennisvang/tufup#52]
I already have some users using an exe compiled with pyupdater, how can I push out an update that switches them over to this library ?

**Comment by KelvinSan** [comment]
Can I do this without the versions.gz and keys.gz files ?

**Comment by dennisvang** [comment]
@KelvinSan The versions.gz and keys.gz are required to create a final update using PyUpdater. You'll need to keep serving those files until *all* your clients have been migrated to tufup.

**Comment by dennisvang** [comment]
@KelvinSan Just curious: Did you succeed in making it work?
