### ISSUE TITLE
Option not to utilize patch files

### ISSUE THREAD

**Issue by kubapilch** [dennisvang/tufup#67]
**Describe the bug**
Creating the patch file can take x4 the time it takes to generate a new version archive, while the file is marginally smaller. 

I am releasing the updates on a raspberry pi 4 which is not a powerful computer but the target device is also a raspberry pi so I am restricted to that device.  

Generating a new update archive takes around 10 minutes while the patch can sometimes take over an hour, the difference in the file size is only around 20-30mb. This behavior is consistent across multiple project that we are developing and use tufup.

**To Reproduce**
1. Create a project on Raspberry Pi
2. Pack the application with PyInstaller using directory option
3. Generate update and patch files

**Expected behavior**
An option to skip the generation of patch files while creating a new release.

**Screenshots**
![image](https://user-images.githubusercontent.com/21139232/221036165-7a70eca1-d4dd-40a7-bc41-b91d0db6163c.png)

**System info (please complete the following information):**
 - OS: Raspbian 
 - Python version [e.g.3.10.6]: 3.9

**Additional context**
python = "3.9.*"
numpy = "1.23.1"
sounddevice = "0.4.4"
tufup = "0.4.8"
pandas = "1.4.3"
pytz = "2022.1"
"RPi.GPIO" = "0.7.1"
spidev = "3.5"
setuptools = "61.0.0"
kivy = {git = "https://github.com/kivy/kivy.git", rev = "2.1.0"}
kivymd = "^1.1.1"

**Comment by dennisvang** [comment]
@kubapilch Although I am not strongly opposed to making patches optional, I'm not sure it is necessary in your case.

Perhaps your *step 2* ("Pack the application with PyInstaller using directory option") *must* be done on the RaspberryPi, but, as far as I can tell, your *step 3* ("Generate update and patch files") does *not* need to be done on the Raspberry Pi. You should be able to do that on another system, using the PyInstaller bundle created on the Raspberry Pi in *step 2*.

Have you tried creating the update archives on a "normal" desktop/laptop system? For example, on my old laptop, creating a diff for a 200MB archive takes up to a few minutes.

**Comment by kubapilch** [comment]
@dennisvang My team is using a whole development pipeline that automates a creation of new releases. 

PyInstaller bundle has A LOT of small files that make transferring of the app folder over the internet undoable in a reasonable amount of time, doing that with a USB drive kills the whole CD pipeline.

If this is what we have to do, then we will adapt to that, but it would be a nice feature that our team would greatly benefit from.

**Comment by dennisvang** [comment]
> ... it would be a nice feature that our team would greatly benefit from.

@kubapilch The workflow is still not completely clear to me, but it sounds good enough. I'll have a look at adding the option.

**Comment by dennisvang** [comment]
> ... Maybe adding a callback function that will spit out the progress would be a way to go, to indicate that it is not stuck but still generating and how much longer it's going to take.

@kubapilch Thanks for the clarification. Looks like optional patches would indeed be the way to go. I've opened PR #68 so you can follow progress there.

Are you using `Repository.add_bundle()` directly, or are you using the command line interface?

As for the progress callback, that would be nice indeed, but, we use `bsdiff4` and I don't think they provide any hooks to make that possible.

**Comment by kubapilch** [comment]
@dennisvang Thanks for such a quick response.  

> Are you using Repository.add_bundle() directly, or are you using the command line interface?

In our pipelines, we are executing slightly modified python scripts provided by you in the tufup example repository, so that is already solving the problem for us. Adding that to CLI would also be amazing. 

> As for the progress callback, that would certainly be nice, but, we use bsdiff4 and I don't think they provide any hooks to make that possible.

It is a shame, but fully understandable.

> Thanks for the clarification. Looks like optional patches would indeed be the way to go. I've opened PR https://github.com/dennisvang/tufup/pull/68 so you can follow progress there.

I have subscribed to the repository notifications, so as soon as you release it to PyPI we will update our workflow.

**Comment by dennisvang** [comment]
@kubapilch After some testing it looks like this works. Note I renamed the `make_patch` argument to `skip_patch`, and added a `--skip-patch` (`-s`) option for the CLI command: `tufup targets add -s ...`

I've released v0.4.9, which is now available on PyPi.

**Comment by dennisvang** [comment]
Closing this for now. Please let me know if you run into any problems.
