### ISSUE TITLE
Split download update and apply update

### ISSUE THREAD

**Issue by wickeat** [dennisvang/tufup#76]
The current `Client.download_and_apply_update()` groups the update download (`_download_updates()`) and update install (`_apply_updates()`) into one function. Could this function possibly be better broken up into two separate functions, allowing the client side implementation to perform additional logic between these 2 steps ? For example, the use case I have in mind is to allow for a prompt to be shown to the user, allowing them to save or shut down their work before performing the update.

**Comment by dennisvang** [comment]
> For example, the use case I have in mind is to allow for a prompt to be shown to the user, allowing them to save or shut down their work before performing the update.

@wickeat It would be more appropriate to do this right after checking for updates using `check_for_updates()`, so *before* calling `download_and_apply_update()`.

For this reason, `check_for_updates()` returns the [version info of the latest available update][2].

Moreover, `Client._apply_updates()` includes a [confirmation step][1]. So, it is always possible to abort before starting the installation, unless you set `skip_confirmation=True`.

Also see [relevant code in tufup-example][3].

[1]: https://github.com/dennisvang/tufup/blob/6d2c707adc66fd7637739f31f9859b0298a4053d/src/tufup/client.py#L270
[2]: https://github.com/dennisvang/tufup/blob/6d2c707adc66fd7637739f31f9859b0298a4053d/src/tufup/client.py#L211
[3]: https://github.com/dennisvang/tufup-example/blob/fc1298d2631bee55d3d8559b78242b81d9d82836/src/myapp/__init__.py#L37

**Comment by dennisvang** [comment]
@wickeat I [updated tufup-example][1] to make this more explicit.

[1]: https://github.com/dennisvang/tufup-example/blob/06fe00f44982cbf4606437cc1c2ad33dc2360e76/src/myapp/__init__.py#L38

**Comment by wickeat** [comment]
Thanks for the reply @dennisvang! 

I understand that the current flow allows for the update checking as a precursor to performing the actual update. However, the use case I was interested in implementing does the update checking *and* update download in a background thread, and then only brings it to the user attention once any update download has finished by bringing the update prompting to the main thread, so that there doesn't have to be unnecessary idle waiting time from the user's POV for the update download. 

Furthermore, the [confirmation step](https://github.com/dennisvang/tufup/blob/6d2c707adc66fd7637739f31f9859b0298a4053d/src/tufup/client.py#L270) isn't a customizable one, so it requires a console to be shown, which is not a given in my use case. 

So, I'm wondering if there is a reason behind the grouping of the update download and update apply steps, and if this justifies their separation.

**Comment by dennisvang** [comment]
> ... However, the use case I was interested in implementing does the update checking _and_ update download in a background thread, and then only brings it to the user attention once any update download has finished by bringing the update prompting to the main thread, ...

@wickeat I see your point. 

The reason for the current grouping was simplicity: "if available then download&install" is just a slightly simpler interface than "if available then download then install"

This was sufficient for our own use case, as we only wanted the user to confirm before the download starts. A minimal implementation of install confirmation on the command line was included for convenience, but I agree this is a bit simplistic.

Note, however, that there is an [`install` hook][1] which you could use for more advanced cases. The easiest solution would be to wrap the [default `install_update` function][2], something like this:

```python
from tufup.utils.platform_specific import install_update


def custom_install(**kwargs):
    # your user confirmation code here
    proceed = ...  # get user input
    # call the default install function
    if proceed:
        install_update(**kwargs)


client.download_and_apply_update(skip_confirmation=True, install=custom_install, ...)
```
The install function is called [here][3].

I haven't tested this specific case, but I guess it should work.

[1]: https://github.com/dennisvang/tufup/blob/6d2c707adc66fd7637739f31f9859b0298a4053d/src/tufup/client.py#L94
[2]: https://github.com/dennisvang/tufup/blob/6d2c707adc66fd7637739f31f9859b0298a4053d/src/tufup/utils/platform_specific.py#L20
[3]: https://github.com/dennisvang/tufup/blob/6d2c707adc66fd7637739f31f9859b0298a4053d/src/tufup/client.py#L274
