### ISSUE TITLE
Make test cases with PyInstaller workflow

### ISSUE THREAD

**Issue by JessicaTegner** [dennisvang/tufup#8]
I propose making a series of tests that goes through an actual PyInstaller and notsotuf  updater workflow (minus the PyInstaller building).

These tests would run after the current ones if possible, so we know that everything *should* work.
So something like the following:

* Initialize repository
* Commit first version of zipped app
* Make patch
* Upload to repo (in this case just sign and move files)
* Run initial app and check if it updates.

This would insure that implementations on all platform we test for will continue to work, regardless of changes internally.

**Comment by dennisvang** [comment]
This is basically what the [examples][1] do. Except that they are not run automatically yet.

[1]: https://github.com/dennisvang/notsotuf/tree/master/examples

**Comment by NicklasTegner** [comment]
Just to clarify. We are not going to implement a specific workflow into notsotuf, but just having it as test cases.
I think this would be a good idea, to make sure that notsotuf doesn't break in a production environment. I mean, for all I care we can use whatever building library, I just know PyInstaller the best, and it seems to be the most widely used.
My whole point, was to have as close to a production environment tested as possible

**Comment by dennisvang** [comment]
> My whole point, was to have as close to a production environment tested as possible

Yes, I understand, and I completely agree that would be a good idea.

I just think PyInstaller should not be part of that test.

This is one point where the `notsotuf` approach deviates from the `pyupdater` approach: We do not want to meddle with any build tools like PyInstaller. We just care about the output of the build tool, which is just a bunch of files and folders with a program somewhere in the mix. In the case of PyInstaller, that would be the bundle found in the `dist` folder.

`notsotuf` can archive those files and folders, create a patch, sign and distribute them, etc. On the client side it can download, unpack, and "install" the files. That's it.
 
So, I would interpret "as close to a production environment as possible" as an environment where we have just a bunch of files and folders, including a minimal python script that runs the `notsotuf` client. If the client can update itself, that means it works.

You are right, it would be a good idea to implement the whole cycle as  an integration test that can be automated.

In addition, I've also been working on a companion repository that represents a concrete example of an application that *does* use PyInstaller together with `notsotuf`. It's still a bit of a mess, but I'll publish that shortly, as an illustration.

**Comment by NicklasTegner** [comment]
> Yes, I understand, and I completely agree that would be a good idea.
I just think PyInstaller should not be part of that test.


Ahem, then I might not have been as clear as I want. Don't get me wrong, I was talking about the output from PyInstaller, not actually running PyInstaller in the test case.
It was more with focus on extracting and running the scripts from the typical platform specific application directories, like Applications on mac and "C:/Program Files" on windows.

**Comment by dennisvang** [comment]
@JessicaTegner It's been a while, but I think this can be closed now: 

https://github.com/dennisvang/tufup-example/pull/20 implements a test workflow for a full update-cycle of the tufup-example app, which also uses PyInstaller.
